{-
   Neptune Backend API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   Neptune Backend API API version: 2.8
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : NeptuneBackend.API
-}

module Neptune.Backend.API
  ( module Neptune.Backend.API.ApiDefault
  ) where

import           Neptune.Backend.API.ApiDefault
