{-
   Neptune Backend API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   Neptune Backend API API version: 2.8
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Neptune.Backend.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module Neptune.Backend.Logging
  ( module Neptune.Backend.LoggingKatip
  ) where

import Neptune.Backend.LoggingKatip

#else

module Neptune.Backend.Logging
  ( module Neptune.Backend.LoggingMonadLogger
  ) where

import Neptune.Backend.LoggingMonadLogger

#endif
