{-
   Neptune Backend API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.1
   Neptune Backend API API version: 2.8
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : NeptuneBackend.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module NeptuneBackend.Logging
  ( module NeptuneBackend.LoggingKatip
  ) where

import NeptuneBackend.LoggingKatip

#else

module NeptuneBackend.Logging
  ( module NeptuneBackend.LoggingMonadLogger
  ) where

import NeptuneBackend.LoggingMonadLogger

#endif
